spring:
  datasource:
    source:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.55:3306/spexregister?useSSL=false
      username: root
      password: Gammabetaalpha314
    target:
      url: jdbc:mysql://192.168.1.55:3307/spexregister
      username: root
      password: Gammabetaalpha314
spexregister:
  crypto:
    secret-key: ${SECRET_KEY}
    initialization-vector: ${IV}
    algorithm: "AES/CFB/PKCS5Padding"
